name: Unit Tests
description: Unit Tests

runs:
  using: composite
  steps:
    - name: Run Unit Tests
      id: unit-tests
      shell: bash
      run: |
        echo "some unit tests"
        pwd
        if [ -f ./test/run-tests.sh ]; then
          source ./test/run-tests.sh
          echo -n $FILE_LOCATIONS > $(results.test-result-file-paths.path)
          echo -n $TEST_TYPES > $(results.test-types.path)
        else
          echo "Test runner script not found: ./test/run-tests.sh"
        fi
